#!/usr/bin/bash
# Monitoring the disk space -- Finding the disk space users in various directories

#######################

# You can add the directories here to monitor.
CHECK_DIR=" /var/log /home"

##############MAIN SCRIPT##############

DATE=$(date '+%m%d%y')

exec > disk_space_$DATE.rpt

echo "Top Ten Disk Space Usage"
echo "for $CHECK_DIR Directories"

for DIR_CHECK in $CHECK_DIR
do
	echo ""
	echo "The $DIR_CHECK Directory: "

	# Creating a list of top ten disk space users in this dir
	du -S $DIR_CHECK 2>/dev/null | sort -rn | sed '{11,$D; =}' | sed 'N; s/\n/ /' | gawk '{printf $1 ":" "\t" $2 "\t" $3 "\n"}'
done

exit

